// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC22m-cAN2mUpjRwxFHJX55XxqCaXEzQ4E',
    appId: '1:496140435082:web:19fdf88861e5b5336ff773',
    messagingSenderId: '496140435082',
    projectId: 'osman-moskee',
    authDomain: 'osman-moskee.firebaseapp.com',
    databaseURL: 'https://osman-moskee-default-rtdb.firebaseio.com',
    storageBucket: 'osman-moskee.firebasestorage.app',
    measurementId: 'G-5LG2GGRYQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6zkQUA6CVGmG6YlvaVyBTks6VXyKvFXA',
    appId: '1:496140435082:android:3e70cdab14d2e2196ff773',
    messagingSenderId: '496140435082',
    projectId: 'osman-moskee',
    databaseURL: 'https://osman-moskee-default-rtdb.firebaseio.com',
    storageBucket: 'osman-moskee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHTs_P5mMTvKb3rfLkW4q-NC4HvkqJQN8',
    appId: '1:496140435082:ios:45d4fff12e78b2df6ff773',
    messagingSenderId: '496140435082',
    projectId: 'osman-moskee',
    databaseURL: 'https://osman-moskee-default-rtdb.firebaseio.com',
    storageBucket: 'osman-moskee.firebasestorage.app',
    androidClientId: '496140435082-v04h3t34a8oe0qp4bbpqce9k8ccctri7.apps.googleusercontent.com',
    iosClientId: '496140435082-uscpikpujqc9o4ghkf9o8n9nn8ut7its.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranCenterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHTs_P5mMTvKb3rfLkW4q-NC4HvkqJQN8',
    appId: '1:496140435082:ios:45d4fff12e78b2df6ff773',
    messagingSenderId: '496140435082',
    projectId: 'osman-moskee',
    databaseURL: 'https://osman-moskee-default-rtdb.firebaseio.com',
    storageBucket: 'osman-moskee.firebasestorage.app',
    androidClientId: '496140435082-v04h3t34a8oe0qp4bbpqce9k8ccctri7.apps.googleusercontent.com',
    iosClientId: '496140435082-uscpikpujqc9o4ghkf9o8n9nn8ut7its.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranCenterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG3L2YSNbUxoNTEncRAcHuqirIdN-oiWY',
    appId: '1:496140435082:web:af2dee2e7e048a4a6ff773',
    messagingSenderId: '496140435082',
    projectId: 'osman-moskee',
    authDomain: 'osman-moskee.firebaseapp.com',
    databaseURL: 'https://osman-moskee-default-rtdb.firebaseio.com',
    storageBucket: 'osman-moskee.firebasestorage.app',
    measurementId: 'G-QCTDN0QJ6Q',
  );

}